[phases.setup]
providers = ["node"]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "echo ZONE_START && ls dist/cli/index.js dist/ui/index.html 2>&1 && node dist/cli/index.js serve"