import path from "node:path";
import type { ApplyResultItem, LlmPatchPlan } from "../types/agent.js";
import type { PatchValidationIssue } from "../types/patch.js";
import { backupFile } from "./backupFile.js";
import {
  ensureDir,
  fileExists,
  readTextFile,
  writeTextFile,
  sanitizeFileName
} from "../utils/files.js";

function formatSchemaIssues(issues: PatchValidationIssue[]): string {
  if (!issues.length) {
    return "none";
  }

  return issues
    .map((issue) => {
      const location = issue.filePath ? ` [${issue.filePath}]` : "";
      return `- ${issue.level.toUpperCase()}: ${issue.message}${location}`;
    })
    .join("\n");
}

function hasBlockingSchemaErrors(issues: PatchValidationIssue[]): boolean {
  return issues.some((issue) => issue.level === "error");
}

export async function applyPatchPlan(input: {
  targetPath: string;
  patchPlan: LlmPatchPlan;
  mode: "dry-run" | "apply";
  schemaPatchWarnings?: PatchValidationIssue[];
}): Promise<ApplyResultItem[]> {
  const cacheDir = path.join(input.targetPath, ".agent-patches");
  const backupRoot = path.join(input.targetPath, ".agent-backups");

  await ensureDir(cacheDir);
  await ensureDir(backupRoot);

  const results: ApplyResultItem[] = [];
  const schemaIssues = input.schemaPatchWarnings ?? [];
  const schemaIssueText = formatSchemaIssues(schemaIssues);
  const blockingSchemaErrors = hasBlockingSchemaErrors(schemaIssues);

  for (const patch of input.patchPlan.patches) {
    const absoluteTargetPath = path.join(input.targetPath, patch.path);
    const exists = await fileExists(absoluteTargetPath);

    if (patch.operation === "create") {
      if (blockingSchemaErrors) {
        results.push({
          path: patch.path,
          action: "skipped",
          reason: "Schema validation contains blocking errors; skipped create operation"
        });
        continue;
      }

      if (input.mode === "dry-run") {
        results.push({
          path: patch.path,
          action: "skipped",
          reason: "Dry-run mode: file creation preview only"
        });
        continue;
      }

      if (exists) {
        results.push({
          path: patch.path,
          action: "skipped",
          reason: "Target file already exists, skipped create operation"
        });
        continue;
      }

      const content = `/* Generated by zone */
${patch.contentPreview}
`;

      await writeTextFile(absoluteTargetPath, content);

      results.push({
        path: patch.path,
        action: "created",
        outputPath: absoluteTargetPath,
        reason:
          schemaIssues.length > 0
            ? "Created new file from patch preview (schema warnings were present; review recommended)"
            : "Created new file from patch preview"
      });

      continue;
    }

    if (patch.operation === "modify") {
      const patchFileName = sanitizeFileName(patch.path) + ".patch-preview.txt";
      const patchOutputPath = path.join(cacheDir, patchFileName);

      let originalContent = "";
      if (exists) {
        originalContent = await readTextFile(absoluteTargetPath);
      }

      const patchDocument = [
        `PATCH TARGET: ${patch.path}`,
        `SUMMARY: ${patch.summary}`,
        `TARGET HINT: ${patch.targetHint}`,
        `MODE: ${input.mode}`,
        "",
        "=== SCHEMA VALIDATION ===",
        schemaIssueText,
        "",
        "=== ORIGINAL FILE PREVIEW (TRUNCATED) ===",
        originalContent.slice(0, 4000),
        "",
        "=== AGENT PATCH PREVIEW ===",
        patch.contentPreview
      ].join("\n");

      if (input.mode === "apply" && exists) {
        await backupFile(absoluteTargetPath, backupRoot);
      }

      await writeTextFile(patchOutputPath, patchDocument);

      results.push({
        path: patch.path,
        action: "patched-file-generated",
        outputPath: patchOutputPath,
        reason:
          blockingSchemaErrors
            ? "Generated patch preview file only because schema validation contains blocking errors"
            : input.mode === "dry-run"
              ? "Dry-run mode: generated patch preview file"
              : schemaIssues.length > 0
                ? "Apply mode: generated patch preview file and backup; schema warnings present"
                : "Apply mode: generated patch preview file and created backup if original existed"
      });
    }
  }

  return results;
}
